import QtQuick

QtObject {
    readonly property color primary: "#f4b2e2"
    readonly property color primaryForeground: "#4e1e46"
    readonly property color primaryContainer: "#67355d"
    readonly property color primaryContainerForeground: "#ffd7f1"
    readonly property color secondary: "#dbbed1"
    readonly property color secondaryForeground: "#3e2a39"
    readonly property color secondaryContainer: "#56404f"
    readonly property color secondaryContainerForeground: "#f9daed"
    readonly property color tertiary: "#f5b9a4"
    readonly property color tertiaryForeground: "#4c2618"
    readonly property color tertiaryContainer: "#663c2d"
    readonly property color tertiaryContainerForeground: "#ffdbcf"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#181216"
    readonly property color backgroundForeground: "#ecdfe5"
    readonly property color surface: "#181216"
    readonly property color surfaceForeground: "#ecdfe5"
    readonly property color surfaceVariantForeground: "#d2c2ca"
    readonly property color surfaceVariant: "#4e444a"
    readonly property color surfaceContainerLowest: "#120c10"
    readonly property color surfaceContainerLow: "#201a1e"
    readonly property color surfaceContainer: "#241e22"
    readonly property color surfaceContainerHigh: "#2f282c"
    readonly property color surfaceContainerHighest: "#3a3337"
    readonly property color outline: "#9b8d95"
    readonly property color outlineVariant: "#4e444a"
    readonly property color shadow: "#000000"
}
