import QtQuick

QtObject {
    readonly property color primary: "#f1be6d"
    readonly property color primaryForeground: "#432c00"
    readonly property color primaryContainer: "#604100"
    readonly property color primaryContainerForeground: "#ffdead"
    readonly property color secondary: "#dbc3a1"
    readonly property color secondaryForeground: "#3d2e16"
    readonly property color secondaryContainer: "#55442a"
    readonly property color secondaryContainerForeground: "#f9dfbb"
    readonly property color tertiary: "#b5cea4"
    readonly property color tertiaryForeground: "#223518"
    readonly property color tertiaryContainer: "#384c2c"
    readonly property color tertiaryContainerForeground: "#d1eabe"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#18130b"
    readonly property color backgroundForeground: "#ece1d4"
    readonly property color surface: "#18130b"
    readonly property color surfaceForeground: "#ece1d4"
    readonly property color surfaceVariantForeground: "#d2c4b4"
    readonly property color surfaceVariant: "#4e4539"
    readonly property color surfaceContainerLowest: "#120d07"
    readonly property color surfaceContainerLow: "#201b13"
    readonly property color surfaceContainer: "#241f17"
    readonly property color surfaceContainerHigh: "#2f2921"
    readonly property color surfaceContainerHighest: "#3a342b"
    readonly property color outline: "#9b8f80"
    readonly property color outlineVariant: "#4e4539"
    readonly property color shadow: "#000000"
}
