import QtQuick

QtObject {
    readonly property color primary: "#ddb9f8"
    readonly property color primaryForeground: "#402357"
    readonly property color primaryContainer: "#573a6f"
    readonly property color primaryContainerForeground: "#f2daff"
    readonly property color secondary: "#d1c1d9"
    readonly property color secondaryForeground: "#372c3f"
    readonly property color secondaryContainer: "#4e4256"
    readonly property color secondaryContainerForeground: "#eeddf6"
    readonly property color tertiary: "#f4b7bc"
    readonly property color tertiaryForeground: "#4c2529"
    readonly property color tertiaryContainer: "#663a3f"
    readonly property color tertiaryContainerForeground: "#ffdadb"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#151217"
    readonly property color backgroundForeground: "#e8e0e8"
    readonly property color surface: "#151217"
    readonly property color surfaceForeground: "#e8e0e8"
    readonly property color surfaceVariantForeground: "#cdc4ce"
    readonly property color surfaceVariant: "#4b454d"
    readonly property color surfaceContainerLowest: "#100d12"
    readonly property color surfaceContainerLow: "#1e1a20"
    readonly property color surfaceContainer: "#221e24"
    readonly property color surfaceContainerHigh: "#2d292e"
    readonly property color surfaceContainerHighest: "#383339"
    readonly property color outline: "#968e98"
    readonly property color outlineVariant: "#4b454d"
    readonly property color shadow: "#000000"
}
