#!/usr/bin/env bash

EWW_BIN="eww"
EWW_CFG="$HOME/dotfiles/config/eww/bar"

calendar() {
LOCK_FILE="$HOME/.cache/eww-calendar.lock"

run() {
    ${EWW_BIN} -c ${EWW_CFG} open calendar
}

if [[ ! -f "$LOCK_FILE" ]]; then
    ${EWW_BIN} -c ${EWW_CFG} close system music_win audio_ctl 2>/dev/null
    touch "$LOCK_FILE"
    run
else
    ${EWW_BIN} -c ${EWW_CFG} close calendar
    rm "$LOCK_FILE"
fi
}

system() {
LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"

run() {
    ${EWW_BIN} -c ${EWW_CFG} open system
}

if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    ${EWW_BIN} -c ${EWW_CFG} close calendar music_win audio_ctl 2>/dev/null
    touch "$LOCK_FILE_MEM"
    run
else
    ${EWW_BIN} -c ${EWW_CFG} close system
    rm "$LOCK_FILE_MEM"
fi
}

music() {
LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"

run() {
    ${EWW_BIN} -c ${EWW_CFG} open music_win
}

if [[ ! -f "$LOCK_FILE_SONG" ]]; then
    ${EWW_BIN} -c ${EWW_CFG} close system calendar 2>/dev/null
    touch "$LOCK_FILE_SONG"
    run
else
    ${EWW_BIN} -c ${EWW_CFG} close music_win
    rm "$LOCK_FILE_SONG"
fi
}

audio() {
LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"

run() {
    ${EWW_BIN} -c ${EWW_CFG} open audio_ctl
}

if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    ${EWW_BIN} -c ${EWW_CFG} close system calendar music_win 2>/dev/null
    touch "$LOCK_FILE_AUDIO"
    run
else
    ${EWW_BIN} -c ${EWW_CFG} close audio_ctl
    rm "$LOCK_FILE_AUDIO"
fi
}

if [ "$1" = "calendar" ]; then
    calendar
elif [ "$1" = "system" ]; then
    system
elif [ "$1" = "music" ]; then
    music
elif [ "$1" = "audio" ]; then
    audio
fi
