include my-theme.conf
#include dracula.conf
font_size 10.25
# modify_font cell_height 110%

hide_window_decorations yes

confirm_os_window_close 0

tab_bar_style powerline

detect_urls yes

copy_on_select clipboard

background_image /home/shahid/Pictures/a12.jpg
background_tint 0.9985
background_image_layout cscaled

window_padding_width 5

remember_window_size  no


# BEGIN_KITTY_FONTS
font_family      family="GeistMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
