#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww -c $HOME/dotfiles/config/eww/bar"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
         bar
        
}

## Launch or close widgets accordingly
if [[ ! `pidof eww` ]] || [[ ! -f "$FILE" ]]; then
	rm -f "$FILE"
	touch "$FILE"
	run_eww
else
	${EWW} close-all && killall eww
	rm -f "$FILE"
fi
