import QtQuick

QtObject {
    readonly property color primary: "#a0cafd"
    readonly property color primaryForeground: "#003258"
    readonly property color primaryContainer: "#1a4975"
    readonly property color primaryContainerForeground: "#d1e4ff"
    readonly property color secondary: "#bbc7db"
    readonly property color secondaryForeground: "#253140"
    readonly property color secondaryContainer: "#3b4858"
    readonly property color secondaryContainerForeground: "#d7e3f8"
    readonly property color tertiary: "#d7bee4"
    readonly property color tertiaryForeground: "#3b2948"
    readonly property color tertiaryContainer: "#523f5f"
    readonly property color tertiaryContainerForeground: "#f3daff"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#111418"
    readonly property color backgroundForeground: "#e1e2e8"
    readonly property color surface: "#111418"
    readonly property color surfaceForeground: "#e1e2e8"
    readonly property color surfaceVariantForeground: "#c3c6cf"
    readonly property color surfaceVariant: "#43474e"
    readonly property color surfaceContainerLowest: "#0b0e13"
    readonly property color surfaceContainerLow: "#191c20"
    readonly property color surfaceContainer: "#1d2024"
    readonly property color surfaceContainerHigh: "#272a2f"
    readonly property color surfaceContainerHighest: "#32353a"
    readonly property color outline: "#8d9199"
    readonly property color outlineVariant: "#43474e"
    readonly property color shadow: "#000000"
}
