import QtQuick

QtObject {
    readonly property color primary: "#9acbfa"
    readonly property color primaryForeground: "#003352"
    readonly property color primaryContainer: "#0a4a72"
    readonly property color primaryContainerForeground: "#cde5ff"
    readonly property color secondary: "#b9c8da"
    readonly property color secondaryForeground: "#233240"
    readonly property color secondaryContainer: "#394857"
    readonly property color secondaryContainerForeground: "#d4e4f6"
    readonly property color tertiary: "#d2bfe7"
    readonly property color tertiaryForeground: "#382a4a"
    readonly property color tertiaryContainer: "#4f4061"
    readonly property color tertiaryContainerForeground: "#eddcff"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#101418"
    readonly property color backgroundForeground: "#e0e2e8"
    readonly property color surface: "#101418"
    readonly property color surfaceForeground: "#e0e2e8"
    readonly property color surfaceVariantForeground: "#c2c7cf"
    readonly property color surfaceVariant: "#42474e"
    readonly property color surfaceContainerLowest: "#0b0f12"
    readonly property color surfaceContainerLow: "#181c20"
    readonly property color surfaceContainer: "#1c2024"
    readonly property color surfaceContainerHigh: "#272a2e"
    readonly property color surfaceContainerHighest: "#313539"
    readonly property color outline: "#8c9198"
    readonly property color outlineVariant: "#42474e"
    readonly property color shadow: "#000000"
}
