import QtQuick

QtObject {
    readonly property color primary: "#82d5c8"
    readonly property color primaryForeground: "#003731"
    readonly property color primaryContainer: "#005048"
    readonly property color primaryContainerForeground: "#9ef2e4"
    readonly property color secondary: "#b1ccc6"
    readonly property color secondaryForeground: "#1c3531"
    readonly property color secondaryContainer: "#334b47"
    readonly property color secondaryContainerForeground: "#cce8e2"
    readonly property color tertiary: "#adcae6"
    readonly property color tertiaryForeground: "#153349"
    readonly property color tertiaryContainer: "#2d4961"
    readonly property color tertiaryContainerForeground: "#cce5ff"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#0e1513"
    readonly property color backgroundForeground: "#dde4e1"
    readonly property color surface: "#0e1513"
    readonly property color surfaceForeground: "#dde4e1"
    readonly property color surfaceVariantForeground: "#bec9c6"
    readonly property color surfaceVariant: "#3f4947"
    readonly property color surfaceContainerLowest: "#090f0e"
    readonly property color surfaceContainerLow: "#161d1c"
    readonly property color surfaceContainer: "#1a211f"
    readonly property color surfaceContainerHigh: "#252b2a"
    readonly property color surfaceContainerHighest: "#303635"
    readonly property color outline: "#899390"
    readonly property color outlineVariant: "#3f4947"
    readonly property color shadow: "#000000"
}
