pragma Singleton

import QtQuick

// Generated by matugen — do not edit by hand.
QtObject {
    readonly property color primary: "#ebc06c"
    readonly property color primaryForeground: "#412d00"

    readonly property color primaryContainer: "#5d4200"
    readonly property color primaryContainerForeground: "#ffdea3"

    readonly property color secondary: "#d9c4a0"
    readonly property color secondaryForeground: "#3b2f15"

    readonly property color secondaryContainer: "#53452a"
    readonly property color secondaryContainerForeground: "#f6e0bb"

    readonly property color tertiary: "#b2cfa8"
    readonly property color tertiaryForeground: "#1e361a"

    readonly property color tertiaryContainer: "#344d2f"
    readonly property color tertiaryContainerForeground: "#cdebc2"

    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"

    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"

    readonly property color background: "#17130b"
    readonly property color backgroundForeground: "#ebe1d4"

    readonly property color surface: "#17130b"
    readonly property color surfaceForeground: "#ebe1d4"

    readonly property color surfaceVariant: "#4e4639"
    readonly property color surfaceVariantForeground: "#d1c5b4"

    readonly property color surfaceContainerLowest: "#120e07"
    readonly property color surfaceContainerLow: "#201b13"
    readonly property color surfaceContainer: "#241f17"
    readonly property color surfaceContainerHigh: "#2e2921"
    readonly property color surfaceContainerHighest: "#3a342b"

    readonly property color outline: "#9a8f80"
    readonly property color outlineVariant: "#4e4639"

    readonly property color shadow: "#000000"
}
