pragma Singleton

import QtQuick

// Generated by matugen — do not edit by hand.
QtObject {
    readonly property color primary: "#d2bcfd"
    readonly property color primaryForeground: "#38265c"

    readonly property color primaryContainer: "#4f3d74"
    readonly property color primaryContainerForeground: "#eaddff"

    readonly property color secondary: "#cdc2db"
    readonly property color secondaryForeground: "#342d40"

    readonly property color secondaryContainer: "#4b4358"
    readonly property color secondaryContainerForeground: "#e9def8"

    readonly property color tertiary: "#f0b7c6"
    readonly property color tertiaryForeground: "#4a2530"

    readonly property color tertiaryContainer: "#643b46"
    readonly property color tertiaryContainerForeground: "#ffd9e1"

    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"

    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"

    readonly property color background: "#141218"
    readonly property color backgroundForeground: "#e7e0e8"

    readonly property color surface: "#141218"
    readonly property color surfaceForeground: "#e7e0e8"

    readonly property color surfaceVariant: "#49454e"
    readonly property color surfaceVariantForeground: "#cbc4cf"

    readonly property color surfaceContainerLowest: "#0f0d13"
    readonly property color surfaceContainerLow: "#1d1b20"
    readonly property color surfaceContainer: "#211f24"
    readonly property color surfaceContainerHigh: "#2b292f"
    readonly property color surfaceContainerHighest: "#36343a"

    readonly property color outline: "#948f99"
    readonly property color outlineVariant: "#49454e"

    readonly property color shadow: "#000000"
}
