pragma Singleton

import QtQuick

// Generated by matugen — do not edit by hand.
QtObject {
    readonly property color primary: "#e9c16c"
    readonly property color primaryForeground: "#402d00"

    readonly property color primaryContainer: "#5c4300"
    readonly property color primaryContainerForeground: "#ffdf9f"

    readonly property color secondary: "#d8c4a0"
    readonly property color secondaryForeground: "#3b2f15"

    readonly property color secondaryContainer: "#52452a"
    readonly property color secondaryContainerForeground: "#f5e0bb"

    readonly property color tertiary: "#b1cfa9"
    readonly property color tertiaryForeground: "#1d361b"

    readonly property color tertiaryContainer: "#334d30"
    readonly property color tertiaryContainerForeground: "#ccebc4"

    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"

    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"

    readonly property color background: "#17130b"
    readonly property color backgroundForeground: "#ebe1d4"

    readonly property color surface: "#17130b"
    readonly property color surfaceForeground: "#ebe1d4"

    readonly property color surfaceVariant: "#4d4639"
    readonly property color surfaceVariantForeground: "#d0c5b4"

    readonly property color surfaceContainerLowest: "#110e07"
    readonly property color surfaceContainerLow: "#1f1b13"
    readonly property color surfaceContainer: "#241f17"
    readonly property color surfaceContainerHigh: "#2e2921"
    readonly property color surfaceContainerHighest: "#39342b"

    readonly property color outline: "#998f80"
    readonly property color outlineVariant: "#4d4639"

    readonly property color shadow: "#000000"
}
