source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = SF Pro Display

# GENERAL
general {
  disable_loading_bar = false
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Pictures/Wallpapers/wallhaven-7pqvdy.png
  blur_passes = 1
  color = $base
}

# LAYOUT
# label {
#   monitor =
#   text = Layout: $LAYOUT
#   color = $text
#   font_size = 25
#   font_family = $font
#   position = 30, -30
#   halign = left
#   valign = top
# }

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 50
  font_family = $font
  position = -20, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 15
  font_family = $font
  position = -25, -75
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/Pictures/unnamed.png
  size = 175
  border_size = 0
  position = 0, 45
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 250, 40
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  # placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">Shahid Shabbir</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -77
  halign = center
  valign = center
}
