import QtQuick

QtObject {
    readonly property color primary: "#80d4d4"
    readonly property color primaryForeground: "#003737"
    readonly property color primaryContainer: "#004f50"
    readonly property color primaryContainerForeground: "#9cf1f1"
    readonly property color secondary: "#b0cccb"
    readonly property color secondaryForeground: "#1b3434"
    readonly property color secondaryContainer: "#324b4b"
    readonly property color secondaryContainerForeground: "#cce8e7"
    readonly property color tertiary: "#b3c8e9"
    readonly property color tertiaryForeground: "#1c314b"
    readonly property color tertiaryContainer: "#334863"
    readonly property color tertiaryContainerForeground: "#d3e4ff"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#0e1514"
    readonly property color backgroundForeground: "#dde4e3"
    readonly property color surface: "#0e1514"
    readonly property color surfaceForeground: "#dde4e3"
    readonly property color surfaceVariantForeground: "#bec9c8"
    readonly property color surfaceVariant: "#3f4948"
    readonly property color surfaceContainerLowest: "#090f0f"
    readonly property color surfaceContainerLow: "#161d1d"
    readonly property color surfaceContainer: "#1a2121"
    readonly property color surfaceContainerHigh: "#252b2b"
    readonly property color surfaceContainerHighest: "#2f3636"
    readonly property color outline: "#889392"
    readonly property color outlineVariant: "#3f4948"
    readonly property color shadow: "#000000"
}
