import QtQuick

QtObject {
    readonly property color primary: "#80d5cf"
    readonly property color primaryForeground: "#003735"
    readonly property color primaryContainer: "#00504d"
    readonly property color primaryContainerForeground: "#9cf1eb"
    readonly property color secondary: "#b0ccc9"
    readonly property color secondaryForeground: "#1b3533"
    readonly property color secondaryContainer: "#324b49"
    readonly property color secondaryContainerForeground: "#cce8e5"
    readonly property color tertiary: "#b0c9e7"
    readonly property color tertiaryForeground: "#19324a"
    readonly property color tertiaryContainer: "#314962"
    readonly property color tertiaryContainerForeground: "#d0e4ff"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#0e1514"
    readonly property color backgroundForeground: "#dde4e2"
    readonly property color surface: "#0e1514"
    readonly property color surfaceForeground: "#dde4e2"
    readonly property color surfaceVariantForeground: "#bec9c7"
    readonly property color surfaceVariant: "#3f4948"
    readonly property color surfaceContainerLowest: "#090f0f"
    readonly property color surfaceContainerLow: "#161d1c"
    readonly property color surfaceContainer: "#1a2120"
    readonly property color surfaceContainerHigh: "#252b2b"
    readonly property color surfaceContainerHighest: "#2f3635"
    readonly property color outline: "#889391"
    readonly property color outlineVariant: "#3f4948"
    readonly property color shadow: "#000000"
}
