import QtQuick

QtObject {
    readonly property color primary: "#81d3df"
    readonly property color primaryForeground: "#00363c"
    readonly property color primaryContainer: "#004f57"
    readonly property color primaryContainerForeground: "#9ef0fc"
    readonly property color secondary: "#b1cbd0"
    readonly property color secondaryForeground: "#1c3438"
    readonly property color secondaryContainer: "#334b4e"
    readonly property color secondaryContainerForeground: "#cde7ec"
    readonly property color tertiary: "#bac6ea"
    readonly property color tertiaryForeground: "#23304d"
    readonly property color tertiaryContainer: "#3a4664"
    readonly property color tertiaryContainerForeground: "#d9e2ff"
    readonly property color error: "#ffb4ab"
    readonly property color errorForeground: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color errorContainerForeground: "#ffdad6"
    readonly property color background: "#0e1415"
    readonly property color backgroundForeground: "#dee3e4"
    readonly property color surface: "#0e1415"
    readonly property color surfaceForeground: "#dee3e4"
    readonly property color surfaceVariantForeground: "#bfc8ca"
    readonly property color surfaceVariant: "#3f484a"
    readonly property color surfaceContainerLowest: "#090f10"
    readonly property color surfaceContainerLow: "#171d1e"
    readonly property color surfaceContainer: "#1b2122"
    readonly property color surfaceContainerHigh: "#252b2c"
    readonly property color surfaceContainerHighest: "#303637"
    readonly property color outline: "#899294"
    readonly property color outlineVariant: "#3f484a"
    readonly property color shadow: "#000000"
}
