#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#	shahidshabbir-se - https://github.com/shahidshabbir-se/mac-dotfiles

[general]
import = [
  "~/.config/alacritty/rice-colors.toml",
  "~/.config/alacritty/fonts.toml",
]
live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0
command = { program = "afplay", args = ["/System/Library/Sounds/Tink.aiff"] }

[terminal]
shell = { program = "zsh", args = ["-l", "-c", "tmux attach || tmux"] }
